<?php
$ch = curl_init();
$rateData = $block->getAppId();
$url = "https://openweathermap.org/data/2.5/weather?id=1581130&appid=439d4b804bc8187953eb36d2a8c26a02";
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);

$resp = curl_exec($ch);

if ($e = curl_error($ch)) {
    echo $e;
} else {
    $decoded = json_decode($resp);
}

curl_close($ch);

?>

<h2 style="font-weight: bold;">Weather Forecast</h2>
<div class="weather-section" style="display:flex; flex-wrap: wrap;flex-direction: row;">
<div style="margin-right: 20px"><div id="openweathermap-widget-5"></div></div>
<script>window.myWidgetParam ? window.myWidgetParam : window.myWidgetParam = [];  window.myWidgetParam.push({id: 5,cityid: '1581130',appid: 'cf5d053a09e0c1e38f15af7c871bd7e7',units: 'metric',containerid: 'openweathermap-widget-5',  });  (function() {var script = document.createElement('script');script.async = true;script.charset = "utf-8";script.src = "//openweathermap.org/themes/openweathermap/assets/vendor/owm/js/weather-widget-generator.js";var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(script, s);  })();</script>
<p></p>
<div id="openweathermap-widget-1"></div>
<script src='//openweathermap.org/themes/openweathermap/assets/vendor/owm/js/d3.min.js'></script><script>window.myWidgetParam ? window.myWidgetParam : window.myWidgetParam = [];  window.myWidgetParam.push({id: 1,cityid: '1581130',appid: 'cf5d053a09e0c1e38f15af7c871bd7e7',units: 'metric',containerid: 'openweathermap-widget-1',  });  (function() {var script = document.createElement('script');script.async = true;script.charset = "utf-8";script.src = "//openweathermap.org/themes/openweathermap/assets/vendor/owm/js/weather-widget-generator.js";var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(script, s);  })();</script>
