<?php

$newsData = $block->getNews();
$i = 1;

?>

<div class='container'>
    <h2 style="font-weight: bold;">News</h2>
    <?php foreach ($newsData->channel->item as $key => $news) : ?>
        <div class="news-item" onclick="window.open('<?= $block->escapeHtml($news->link) ?>', '_blank').focus()">
            <div class="news-item-image">
                <img src="<?= $news->image ?>" />
            </div>
            <div class="news-item-content">
                <div class="news-item-title">
                    <?= $block->escapeHtml($news->title) ?>
                </div>
                <div class="news-item-description">
                    <?= $news->realDescription ?>
                </div>
                <div class="news-item-pubDate">
                    <?= $block->escapeHtml($news->pubDate) ?>
                </div>
            </div>
        </div>
    <?php $i++;
    endforeach; ?>
</div>

<script>

</script>